version: '3.8'
services:

  postgres-service:
    container_name: postgres-service
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  backend:
    image: backend:dev
    ports:
      - "8080:8080"

  frontend:
    image: frontend:dev
    ports:
      - "3000:3000"